export const EDITOR_WIDTH = 680
export const EXTENDED_EDITOR_WIDTH = 1024
export const EDITOR_HEIGHT = 720

export const EDITOR_HEADER_HEIGHT = 40

export const EDITOR_BODY_HEIGHT = EDITOR_HEIGHT - EDITOR_HEADER_HEIGHT
